### ISSUE TITLE
Player Details function breaks on first use

### ISSUE THREAD

**Issue by NottCurious** [NottCurious/TMIndiaBot#11]
Command breaks when you use the username for the first time but works when you use the same function with same username again.

**Comment by NottCurious** [comment]
thought I fixed it, but it's back

```
python.exe .\main.py17:32:12 [INFO] - [main.py > <module>() > 19] - Logging Setup for main.py
17:32:12 [INFO] - [main.py > <module>() > 21] - Reading Bot Token
17:32:12 [INFO] - [main.py > <module>() > 24] - Got Bot Token
17:32:12 [INFO] - [main.py > <module>() > 26] - Creating Client
17:32:12 [INFO] - [main.py > <module>() > 28] - Created Client
17:32:12 [INFO] - [main.py > <module>() > 30] - Creating Thread for NPM Module
17:32:12 [INFO] - [main.py > <module>() > 38] - Thread Created for NPM Module
17:32:12 [INFO] - [main.py > <module>() > 40] - Starting Bot Startup
17:32:12 [INFO] - [file_check.py > file_check() > 10] - Starting File Check
17:32:12 [DEBUG] - [file_check.py > file_check() > 14] - Checking for Times Run File
17:32:12 [INFO] - [main.py > <module>() > 44] - Starting NPM Module thread
17:32:12 [INFO] - [main.py > <module>() > 46] - NPM Module Thread Started
17:32:12 [INFO] - [main.py > <module>() > 47] - NPM Module Initialized, Resuming Bot INIT
17:32:12 [INFO] - [main.py > <module>() > 50] - Loading Slash Cogs
17:32:12 [DEBUG] - [main.py > <module>() > 53] - Loading cogs.generic_slash
17:32:12 [DEBUG] - [main.py > <module>() > 53] - Loading cogs.listeners
17:32:13 [DEBUG] - [listeners.py > __init__() > 27] - Getting Statuses
17:32:13 [DEBUG] - [listeners.py > __init__() > 30] - Status Loading File
17:32:13 [DEBUG] - [listeners.py > __init__() > 34] - Status File Loaded
17:32:13 [DEBUG] - [listeners.py > __init__() > 36] - Received Statuses
17:32:13 [DEBUG] - [main.py > <module>() > 53] - Loading cogs.quote_slash
17:32:13 [DEBUG] - [main.py > <module>() > 53] - Loading cogs.trackmania
17:32:13 [DEBUG] - [main.py > <module>() > 53] - Loading cogs.username_slash
17:32:13 [INFO] - [main.py > <module>() > 55] - Loaded Slash Cogs

> TMIndiaBotApi@1.0.0 start
> node util/node/TMIndiaBotApi/index.js

[INFO EXPRESS] Initialize Middleware
[INFO EXPRESS] Loading routes
[INFO EXPRESS] Listening on http://localhost:3000
[INFO EXPRESS] Route loaded - /tm2020/cotd/:id from Routes/flag.js
[INFO EXPRESS] Route loaded - /tmnf-x/leaderboard/:tmxid from tmnf-x/leaderboard.js
[INFO EXPRESS] Route loaded - /tmnf-x/stylesearch/:type from tmnf-x/stylesearch.js
[INFO EXPRESS] Route loaded - /tmnf-x/trackinfo/:tmxid from tmnf-x/trackinfo.js
[INFO EXPRESS] Route loaded - /tm2020/cotd/:id from tm2020/COTDwID.js
[INFO EXPRESS] Route loaded - /tm2020/campaign/famous from tm2020/latestCampaign.js
[INFO EXPRESS] Route loaded - /tm2020/cotd/latest from tm2020/latestCOTD.js
[INFO EXPRESS] Route loaded - /tm2020/leaderboard/:trackid/:from from tm2020/leaderboard.js
[INFO EXPRESS] Route loaded - /tm2020/player/:username from tm2020/player.js
[INFO EXPRESS] Route loaded - /tm2020/player/:playerid/cotd from tm2020/playerCotdInfo.js
[INFO EXPRESS] Route loaded - /tm2020/random-map from tm2020/randomMap.js
[INFO EXPRESS] Route loaded - /tm2020/campaign/search/:searchText from tm2020/searchCampaign.js
[INFO EXPRESS] Route loaded - /tm2020/trackinfo/:trackid from tm2020/trackinfo.js
[INFO EXPRESS] All routes loaded
17:32:16 [CRITICAL] - [listeners.py > on_ready() > 44] - Bot Logged In
17:32:16 [DEBUG] - [listeners.py > on_ready() > 47] - Reading Value from Times Run File
17:32:16 [DEBUG] - [listeners.py > on_ready() > 53] - Starting Keep Alive Loop
17:32:16 [DEBUG] - [listeners.py > on_ready() > 55] - Started Keep Alive Loop
17:32:16 [DEBUG] - [listeners.py > on_ready() > 56] - Start Change Status Loop
17:32:16 [DEBUG] - [listeners.py > on_ready() > 58] - Started Change Status Loop
17:32:16 [DEBUG] - [listeners.py > on_ready() > 67] - Getting Announcement Channels
17:32:16 [INFO] - [generic_helper.py > print_system_info() > 19] - ------------------------------
17:32:16 [INFO] - [generic_helper.py > print_system_info() > 20] - Hostname: tmindiabot@Deepesh-PC
17:32:16 [INFO] - [generic_helper.py > print_system_info() > 21] - Platform: Windows-10-10.0.22000-SP0
17:32:16 [INFO] - [generic_helper.py > print_system_info() > 22] - Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
17:32:16 [INFO] - [generic_helper.py > print_system_info() > 23] - System: Windows 10
17:32:16 [INFO] - [generic_helper.py > print_system_info() > 24] - Architecture: AMD64
17:32:16 [INFO] - [generic_helper.py > print_system_info() > 25] - Available Ram: 8 GB
17:32:16 [INFO] - [generic_helper.py > print_system_info() > 26] - ------------------------------
17:32:16 [DEBUG] - [listeners.py > on_ready() > 74] - Sending Message in 876335103146623016
17:32:16 [DEBUG] - [keep_alive.py > keep_alive() > 15] - 30 Minutes have passed, Task activated - at 2021-11-19 12:02:16.870166
17:32:16 [DEBUG] - [keep_alive.py > keep_alive() > 16] - Pinging API
17:32:16 [DEBUG] - [keep_alive.py > ping_api() > 31] - Loading Dotenv
17:32:16 [INFO] - [keep_alive.py > ping_api() > 35] - Requesting from API
17:32:16 [DEBUG] - [keep_alive.py > ping_api() > 37] - Creating Thread for API Ping
17:32:16 [INFO] - [keep_alive.py > ping_api() > 41] - Created Thread for Pinging API, Starting
17:32:16 [INFO] - [keep_alive.py > ping_api() > 43] - Request Successful, Joining Thread
17:32:16 [DEBUG] - [keep_alive.py > ping_api() > 45] - Thread Joined
17:32:16 [INFO] - [keep_alive.py > ping_api() > 48] - Successfully Received Data from API
17:32:16 [DEBUG] - [keep_alive.py > keep_alive() > 19] - API Ping Successful
GET / 200 2.047 ms - 27
17:32:16 [DEBUG] - [keep_alive.py > keep_alive() > 22] - Sending Message to Channel to Keep This Damned Thing Alive
17:32:16 [DEBUG] - [keep_alive.py > keep_alive() > 23] - Got Channel Successfully
17:32:16 [DEBUG] - [keep_alive.py > keep_alive() > 25] - Sending Message to Channel
17:32:16 [DEBUG] - [status_change.py > change_status() > 23] - 10 Minutes have Passed, Changing Status at - 2021-11-19 12:02:16.887440
17:32:16 [DEBUG] - [status_change.py > change_status() > 24] - Checking for First Time
17:32:16 [DEBUG] - [status_change.py > change_status() > 26] - First Time is True, returning
No Role ID found in Guild (876042400005505066) for Role (Moderator)
No Role ID found in Guild (876042400005505066) for Role (Bot Developer)
No Role ID found in Guild (876042400005505066) for Role (Admin)
17:32:17 [DEBUG] - [listeners.py > on_ready() > 81] - Sent Message to 876335103146623016
17:32:17 [DEBUG] - [listeners.py > on_ready() > 74] - Sending Message in 880628511512096778
17:32:17 [DEBUG] - [listeners.py > on_ready() > 88] - Can't Send Message to 880628511512096778
17:32:17 [DEBUG] - [listeners.py > on_ready() > 90] - Writing TimesRun to File
17:32:17 [INFO] - [listeners.py > on_ready() > 94] - Bot now Usable
17:32:17 [DEBUG] - [keep_alive.py > keep_alive() > 27] - Sent Message to Channel
17:32:18 [DEBUG] - [player.py > get_player_data() > 47] - Pinging API for Data of NottCurious
GET /tm2020/player/NottCurious 200 2247.718 ms - 874
17:32:20 [DEBUG] - [player.py > get_player_data() > 54] - NottCurious is valid
17:32:20 [DEBUG] - [player.py > get_player_data() > 57] - Parsing Data
17:32:20 [DEBUG] - [player.py > get_player_data() > 62] - Trying for Twitch Data
17:32:20 [DEBUG] - [player.py > get_player_data() > 65] - Twitch Data Exists -> NottCurious
17:32:20 [DEBUG] - [player.py > get_player_data() > 70] - Checking if TMGL Player
17:32:20 [DEBUG] - [player.py > get_player_data() > 76] - NottCurious is not a TMGL Player
17:32:20 [DEBUG] - [player.py > get_player_data() > 78] - Checking for Youtube
17:32:20 [DEBUG] - [player.py > get_player_data() > 84] - NottCurious does not have a youtube listed
17:32:20 [DEBUG] - [player.py > get_player_data() > 86] - Checking for Twitter
17:32:20 [DEBUG] - [player.py > get_player_data() > 92] - NottCurious does not have a twitter listed
17:32:20 [DEBUG] - [easy_embed.py > create_embed() > 24] - Creating Embed with Title - Player Details for NottCurious, description -  and colour - #005dff
17:32:20 [DEBUG] - [easy_embed.py > create_embed() > 30] - Returning <discord.embeds.Embed object at 0x00000245E0C07CA0>
17:32:20 [DEBUG] - [player.py > get_player_data() > 98] - Adding Location for NottCurious
17:32:20 [DEBUG] - [player.py > get_player_data() > 102] - Added Zone: India and Parent Zone: Asia
17:32:20 [DEBUG] - [player.py > get_player_data() > 104] - Parsing Matchmaking Data for NottCurious
17:32:20 [DEBUG] - [player.py > __div_str() > 264] - Converting 5 to string
17:32:20 [DEBUG] - [player.py > __div_str() > 265] - Opening JSON file of ranks
17:32:20 [DEBUG] - [player.py > __div_str() > 267] - Opened file, parsing data
17:32:20 [DEBUG] - [player.py > __div_str() > 270] - Rank is Silver 3
17:32:20 [DEBUG] - [player.py > get_player_data() > 133] - Parsed Matchmaking Data for NottCurious, creating string
17:32:20 [DEBUG] - [player.py > get_player_data() > 140] - Created Matchmaking String, Adding to Embed
17:32:20 [DEBUG] - [player.py > get_player_data() > 144] - Added Matchmaking Data to <discord.embeds.Embed object at 0x00000245E0C07CA0>
17:32:20 [DEBUG] - [player.py > get_player_data() > 146] - Parsing Royal Data for NottCurious
17:32:20 [ERROR] - [player.py > get_player_data() > 167] - NottCurious has never won a Royal match, defaulting percentage to 0
17:32:20 [ERROR] - [player.py > get_player_data() > 177] - NottCurious has never won a Royal match, defaulting to 1
17:32:20 [DEBUG] - [player.py > get_player_data() > 179] - Parsed Royal Data for NottCurious, creating string
17:32:20 [DEBUG] - [player.py > get_player_data() > 187] - Created Royal String, Adding to Embed
17:32:20 [DEBUG] - [player.py > get_player_data() > 189] - Added Royal Data to <discord.embeds.Embed object at 0x00000245E0C07CA0>
17:32:20 [DEBUG] - [player.py > get_player_data() > 191] - Adding COTD Data to Embed
17:32:20 [DEBUG] - [player.py > __get_basic_cotd_data() > 275] - Getting COTD Data for NottCurious
17:32:20 [DEBUG] - [player.py > __get_basic_cotd_data() > 276] - Getting Player ID
17:32:20 [DEBUG] - [player.py > get_player_id() > 30] - Getting Player ID for NottCurious
GET /tm2020/player/NottCurious 200 0.775 ms - 874
17:32:20 [DEBUG] - [player.py > get_player_id() > 32] - Received Player Data, Parsing
17:32:20 [DEBUG] - [player.py > get_player_id() > 34] - Player ID is b73fe3d7-a92a-4a6d-ab9d-49005caec499
17:32:20 [DEBUG] - [player.py > __get_basic_cotd_data() > 278] - Got Player ID
17:32:20 [DEBUG] - [player.py > __get_basic_cotd_data() > 280] - Getting COTD Data
GET /tm2020/player/b73fe3d7-a92a-4a6d-ab9d-49005caec499/cotd 200 659.176 ms - 3339
17:32:21 [DEBUG] - [player.py > __get_basic_cotd_data() > 282] - Got COTD Data
17:32:21 [DEBUG] - [player.py > __get_basic_cotd_data() > 284] - Parsing all COTD Data
17:32:21 [DEBUG] - [cotd.py > _get_avg_div() > 70] - Removing all Incomplete COTDs
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 24] - Looping through COTD Data
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': '835', 'date': '2021-08-26', 'globalRank': 832, 'server': 13, 'serverRank': 'DNF', 'totalPlayer': 2915} at index: 0
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': '754', 'date': '2021-08-14', 'globalRank': 1596, 'server': 25, 'serverRank': 'DNF', 'totalPlayer': 2611} at index: 2
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': 736, 'date': '2021-08-11', 'globalRank': 1344, 'server': 21, 'serverRank': 'DNF', 'totalPlayer': 2801} at index: 3
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': 722, 'date': '2021-08-08', 'globalRank': 1084, 'server': 17, 'serverRank': 'DNF', 'totalPlayer': 2830} at index: 4
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': 677, 'date': '2021-07-30', 'globalRank': 1337, 'server': 21, 'serverRank': 'DNF', 'totalPlayer': 2449} at index: 8
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': 649, 'date': '2021-07-25', 'globalRank': 1403, 'server': 22, 'serverRank': 'DNF', 'totalPlayer': 2834} at index: 11
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': 602, 'date': '2021-07-16', 'globalRank': 1590, 'server': 25, 'serverRank': 'DNF', 'totalPlayer': 2217} at index: 15
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': 548, 'date': '2021-07-08', 'globalRank': 1660, 'server': 26, 'serverRank': 'DNF', 'totalPlayer': 2665} at index: 17
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': 494, 'date': '2021-06-29', 'globalRank': 1584, 'server': 25, 'serverRank': 'DNF', 'totalPlayer': 2254} at index: 20
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': 437, 'date': '2021-06-08', 'globalRank': 1916, 'server': 30, 'serverRank': 'DNF', 'totalPlayer': 3105} at index: 22
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 30] - All Incomplete COTDs Popped, Returning Data
17:32:21 [DEBUG] - [cotd.py > _get_avg_div() > 72] - Removed all COTD Data
17:32:21 [DEBUG] - [cotd.py > _get_avg_div() > 73] - Getting Num of Completed COTDs
17:32:21 [DEBUG] - [cotd.py > _get_num_completed_cotds() > 43] - Removing all incomplete COTDs
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 24] - Looping through COTD Data
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': '748', 'date': '2021-08-13', 'globalRank': 1021, 'server': 16, 'serverRank': 'DNF', 'totalPlayer': 2583} at index: 2
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': 718, 'date': '2021-08-07', 'globalRank': 1274, 'server': 20, 'serverRank': 'DNF', 'totalPlayer': 2527} at index: 3
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 27] - Popping {'compID': 672, 'date': '2021-07-29', 'globalRank': 1790, 'server': 28, 'serverRank': 'DNF', 'totalPlayer': 2389} at index: 6
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 30] - All Incomplete COTDs Popped, Returning Data
17:32:21 [DEBUG] - [cotd.py > _get_num_completed_cotds() > 45] - Removed all COTD Data, Returning Num of Completed
17:32:21 [DEBUG] - [cotd.py > _get_avg_div() > 75] - Num of Completed COTDs: 20
17:32:21 [DEBUG] - [cotd.py > _get_avg_div() > 78] - Looping Through Data
17:32:21 [DEBUG] - [cotd.py > _get_avg_global_rank() > 95] - Removing all Incomplete COTDs
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 24] - Looping through COTD Data
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 30] - All Incomplete COTDs Popped, Returning Data
17:32:21 [DEBUG] - [cotd.py > _get_avg_global_rank() > 97] - Removed all COTD Data
17:32:21 [DEBUG] - [cotd.py > _get_avg_global_rank() > 98] - Getting Num of Completed COTDs
17:32:21 [DEBUG] - [cotd.py > _get_num_completed_cotds() > 43] - Removing all incomplete COTDs
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 24] - Looping through COTD Data
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 30] - All Incomplete COTDs Popped, Returning Data
17:32:21 [DEBUG] - [cotd.py > _get_num_completed_cotds() > 45] - Removed all COTD Data, Returning Num of Completed
17:32:21 [DEBUG] - [cotd.py > _get_avg_global_rank() > 100] - Num of Completed COTDs: 20
17:32:21 [DEBUG] - [cotd.py > _get_avg_global_rank() > 103] - Looping Through Data
17:32:21 [DEBUG] - [cotd.py > _get_num_completed_cotds() > 43] - Removing all incomplete COTDs
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 24] - Looping through COTD Data
17:32:21 [DEBUG] - [cotd.py > _remove_incomplete_cotds() > 30] - All Incomplete COTDs Popped, Returning Data
17:32:21 [DEBUG] - [cotd.py > _get_num_completed_cotds() > 45] - Removed all COTD Data, Returning Num of Completed
17:32:21 [DEBUG] - [player.py > __get_basic_cotd_data() > 289] - Parsed all COTD Data
17:32:21 [DEBUG] - [player.py > __get_basic_cotd_data() > 291] - Making COTD String
17:32:21 [DEBUG] - [player.py > __get_basic_cotd_data() > 293] - Created COTD String
17:32:21 [DEBUG] - [player.py > __get_basic_cotd_data() > 295] - Returning COTD String
17:32:21 [DEBUG] - [player.py > get_player_data() > 195] - Added COTD Data to <discord.embeds.Embed object at 0x00000245E0C07CA0>
17:32:21 [DEBUG] - [player.py > get_player_data() > 197] - Adding Social Media Handles to Embed
17:32:21 [DEBUG] - [player.py > __format_meta_details() > 249] - Twitch Exists for NottCurious, Adding
17:32:21 [DEBUG] - [player.py > __format_meta_details() > 259] - Created Embed, returning <discord.embeds.Embed object at 0x00000245E0C07CA0>
17:32:21 [DEBUG] - [player.py > get_player_data() > 206] - Social Media Handles Added for NottCurious, returning the embed: <discord.embeds.Embed object at 0x00000245E0C07CA0>
Ignoring exception in command <discord.commands.SlashCommand name=player_details>:
Traceback (most recent call last):
  File "z:\GithubRepositories\TMIndiaBot\venv\lib\site-packages\discord\commands\commands.py", line 84, in wrapped
    ret = await coro(arg)
  File "z:\GithubRepositories\TMIndiaBot\venv\lib\site-packages\discord\commands\commands.py", line 526, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "Z:\GithubRepositories\TMIndiaBot\cogs\trackmania.py", line 40, in _player_details
    await ctx.respond(embed=data)
  File "z:\GithubRepositories\TMIndiaBot\venv\lib\site-packages\discord\interactions.py", line 582, in send_message
    await adapter.create_interaction_response(
  File "z:\GithubRepositories\TMIndiaBot\venv\lib\site-packages\discord\webhook\async_.py", line 191, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "z:\GithubRepositories\TMIndiaBot\venv\lib\site-packages\discord\bot.py", line 444, in process_application_commands
    await ctx.command.invoke(ctx)
  File "z:\GithubRepositories\TMIndiaBot\venv\lib\site-packages\discord\commands\commands.py", line 133, in invoke
    await injected(ctx)
  File "z:\GithubRepositories\TMIndiaBot\venv\lib\site-packages\discord\commands\commands.py", line 90, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction     
```

**Comment by NottCurious** [comment]
fixed in latest pycord dev branch
